- project:
#    templates:
#      - docs-on-readthedocs
#      - openstack-python-jobs
#      - openstack-python35-jobs
    vars:
      rtd_webhook_id: '47124'
    check:
      jobs:
        - os-faults-rally
    gate:
      jobs:
        - os-faults-devstack

- job:
    name: os-faults-devstack
    parent: devstack-minimal
    description: |
      Run os-faults integration tests on DevStack under Python 3
    timeout: 2400
    pre-run: os_faults/tests/devstack/playbooks/pre.yml
    run: os_faults/tests/devstack/playbooks/run_on_devstack.yml
    post-run: os_faults/tests/devstack/playbooks/post.yml
    required-projects:
      - openstack/os-faults
    vars:
      tox_envlist: devstack

- job:
    name: os-faults-rally
    parent: rally-task-at-devstack
    timeout: 10800
    pre-run: os_faults/tests/rally/playbooks/pre.yml
    run: os_faults/tests/rally/playbooks/run.yml
    vars:
      devstack_services:
        dstat: true
        etcd3: true
        mysql: true
        peakmem_tracker: true
        rabbit: false
        tls-proxy: true
        # Keystone services
        key: true
        # Glance services
        g-api: false
        g-reg: false
        # Nova services
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        # Neutron services
        # We need to keep using the neutron-legacy based services for
        # now until all issues with the new lib/neutron code are solved
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        # Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
      devstack_localrc:
        RALLY_DEBUG: true
      rally_task: os_faults/tests/rally/task-os-faults.yaml
