- project:
    templates:
      - docs-on-readthedocs
      - openstack-python-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
    vars:
      rtd_webhook_id: '47124'
    check:
      jobs:
        - os-faults-devstack
    gate:
      jobs:
        - os-faults-devstack

- job:
    name: os-faults-devstack
    parent: devstack-minimal
    description: |
      Run os-faults integration tests on DevStack under Python 3
    timeout: 2400
    pre-run: os_faults/tests/devstack/playbooks/pre.yml
    run: os_faults/tests/devstack/playbooks/run_on_devstack.yml
    post-run: os_faults/tests/devstack/playbooks/post.yml
    required-projects:
      - openstack/os-faults
    vars:
      tox_envlist: devstack
      devstack_plugins:
        os-faults: https://git.openstack.org/openstack/os-faults
